
service: node-aws

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  region: sa-east-1
  memorySize: 256
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:GetObject
        - s3:PutObject
      Resource:
        - "arn:aws:s3:::*"

functions:
  hello:
    handler: handler.hello
    enviroment:
      bucket: node-aws-serverless
    events:
      - s3:
          bucket: node-aws-serverless
          event: s3:ObjectCreated:*
          rules:
            - prefix: uploads/
            - suffix: .jpg